version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_vendas
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/raw/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data/processed/views.sql:/docker-entrypoint-initdb.d/02_views.sql
    command: postgres -c listen_addresses='*'
