version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_vendas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vendasdb
    ports:
      - "15432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/02_views.sql
    command: postgres -c listen_addresses='*'
